# Generated by Django 5.2.8 on 2026-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('house_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_time_and_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
