# Generated by Django 5.2.8 on 2026-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_courseclass_userprofile_studentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
