# Generated by Django 5.2.8 on 2026-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='application_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
