# Generated by Django 5.2.8 on 2026-07-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_application_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
