# Generated by Django 5.2.4 on 2026-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title or headline (e.g. Live Class / Zoom Link / Exam Portal)', max_length=255)),
                ('url', models.URLField(help_text='Full destination URL (e.g. https://meet.google.com/...)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions for students')),
                ('publish_at', models.DateTimeField(help_text='Scheduled date and time to display this link to students')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional date and time when this link should automatically expire', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle link active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
    ]
