# Generated by Django 5.2.4 on 2026-09-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_dashboardlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardLink',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when class is displayed to students (blank for immediate display)', null=True),
        ),
    ]
